// Code generated by Kitex v0.4.4. DO NOT EDIT.

package chatservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	chatpart "tiktok/cmd/chat/kitex_gen/chatpart"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetChatHistory(ctx context.Context, Req *chatpart.DouyinMessageChatRequest, callOptions ...callopt.Option) (r *chatpart.DouyinMessageChatResponse, err error)
	DoMessageAction(ctx context.Context, Req *chatpart.DouyinMessageActionRequest, callOptions ...callopt.Option) (r *chatpart.DouyinMessageActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kChatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kChatServiceClient struct {
	*kClient
}

func (p *kChatServiceClient) GetChatHistory(ctx context.Context, Req *chatpart.DouyinMessageChatRequest, callOptions ...callopt.Option) (r *chatpart.DouyinMessageChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetChatHistory(ctx, Req)
}

func (p *kChatServiceClient) DoMessageAction(ctx context.Context, Req *chatpart.DouyinMessageActionRequest, callOptions ...callopt.Option) (r *chatpart.DouyinMessageActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DoMessageAction(ctx, Req)
}
