// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFavorite = "favorites"

// Favorite mapped from table <favorites>
type Favorite struct {
	ID      int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID  int64 `gorm:"column:user_id" json:"user_id"`
	VideoID int64 `gorm:"column:video_id" json:"video_id"`
}

// TableName Favorite's table name
func (*Favorite) TableName() string {
	return TableNameFavorite
}
